#!/usr/bin/env python3
import sys
import subprocess
import os

def build(path):
    if path.startswith("rust"):
        subprocess.run(["cargo", "build", "--release"], cwd=path)
        return f"{path}/target/release/test"
    if path.startswith("python"):
        return f"{path}/test.py"
    raise Exception(f"Not supported path: {path}")

def bench(paths):
    if not os.path.exists("/tmp/file"):
        subprocess.run(["dd", "if=/dev/urandom", "of=/tmp/file", "bs=64M", "count=1"])

    bench_args = ["hyperfine"]

    for path in paths:
        exe_path = build(path)
        bench_args.append(exe_path)

    print(bench_args)
    subprocess.run(bench_args)

if __name__ == "__main__":
    if len(sys.argv) < 1:
        print("Usage: ./bench <subpath1> <subpath2> ...")
        sys.exit(1)

    subpaths = sys.argv[1:]
    bench(subpaths)